
package com.vastlb.wing_me.Classes

import android.annotation.SuppressLint
import android.content.Context
import android.provider.Settings
import android.widget.EditText
import com.vastlb.wing_me.DataClasses.*
import com.vastlb.wing_me.R
import java.text.SimpleDateFormat
import java.util.Locale

class Constants {

    companion object {
        val url = "https://app.wingme.app/v03/"
        val appURL = "https://wingme.app/"
        val deleteAccountURL = "https://app.wingme.app/delete_account"

        var firebaseToken = ""
        var chatUserID = ""
        var chatGroupID = ""

        var datingID = ""
        var socialisingID = ""
        var networkingID = ""

        var inLocation = false

        lateinit var selectMyLocation: () -> Unit

        lateinit var reloadLocation: () -> Unit
        lateinit var reloadMessages: () -> Unit
        lateinit var reloadGroup: () -> Unit
        lateinit var reloadGroups: () -> Unit
        lateinit var reloadProfile: () -> Unit

        lateinit var wingMe: (jsonObject: LocationClass) -> Unit
        lateinit var hideLocation: () -> Unit

        lateinit var commentClass: CommentClass

        var setLastMessage: ((userID: String, message: String, date: String, badge: Boolean) -> Unit)? = null
        var setChatMessage: ((messageID: String, message: String, date: String) -> Unit)? = null
        var setLastGroup: ((groupID: String, message: String, date: String, badge: Boolean) -> Unit)? = null
        var setGroupMessage: ((userName: String, gender: String, messageID: String, message: String, date: String) -> Unit)? = null

        @SuppressLint("HardwareIds")
        fun getUID(context: Context): String {
            val uid = Settings.Secure.getString(context.getContentResolver(), Settings.Secure.ANDROID_ID)
            return uid
        }

        fun deleteUserData(context: Context) {
            val preferences = context.getSharedPreferences("Preferences", Context.MODE_PRIVATE)
            val editor = preferences.edit()
            editor.remove("Token")
            editor.remove("Sent")
            editor.remove("LocationID")
            editor.remove("LocationName")
            editor.remove("Setup")
            editor.remove("LastDate")
            editor.remove("LastLocationNotification")
            editor.remove("LastLocationAlert")
            editor.apply()
        }

        fun getRelationships(index: Int): ArrayList<RelationshipClass> {
            val array = ArrayList<RelationshipClass>()
            array.add(RelationshipClass("1", "Single", index == array.size))
            array.add(RelationshipClass("2", "Dating", index == array.size))
            array.add(RelationshipClass("3", "In a Relationship", index == array.size))
            array.add(RelationshipClass("4", "Married", index == array.size))
            array.add(RelationshipClass("5", "Other", index == array.size))
            return array
        }

        fun getLookingForArray(progress1: Int, progress2: Int, progress3: Int): ArrayList<LookingForClass> {
            val array = ArrayList<LookingForClass>()
            array.add(LookingForClass("Socializing", arrayOf("🚫", "None"), arrayOf("🌎", "Community"), arrayOf("👩🏻‍🤝‍👩🏾", "Close friends"), arrayOf("✈️", "Travel"), progress1))
            array.add(LookingForClass("Business", arrayOf("🚫", "None"), arrayOf("🤝", "Opportunities"), arrayOf("👩🏻‍🏫", "Mentorship"), arrayOf("🧠", "Personal Growth"), progress2))
            array.add(LookingForClass("Love", arrayOf("🚫", "None"), arrayOf("❤️", "Open to love"), arrayOf("🔓", "Taken"), arrayOf("🪩", "Fun"), progress3))
            return array
        }

        fun getLookingFor(datingID: String, socialisingID: String, networkingID: String): String {
            var string = String()

            val datingArray = arrayOf("🌎", "👩🏻‍🤝‍👩🏾", "✈️")
            val socialisingArray = arrayOf("🤝", "👩🏻‍🏫", "🧠")
            val networkingArray = arrayOf("❤️", "🔓", "🪩")

            if (!datingID.isEmpty()) {
                val index = datingID.toInt()

                if (index != 0) {
                    string += "  " + datingArray[index - 1]
                }
            }
            if (!socialisingID.isEmpty()) {
                val index = socialisingID.toInt()

                if (index != 0) {
                    string += "  " + socialisingArray[index - 1]
                }
            }
            if (!networkingID.isEmpty()) {
                val index = networkingID.toInt()

                if (index != 0) {
                    string += "  " + networkingArray[index - 1]
                }
            }
            return string
        }

        fun getCountries(): ArrayList<PickerClass> {
            val array = ArrayList<PickerClass>()
            array.add(PickerClass("Abkhazia 1"                                   ,"7840"))
            array.add(PickerClass("Abkhazia 2"                                   ,"7940"))
            array.add(PickerClass("Afghanistan"                                  ,"93"))
            array.add(PickerClass("Albania"                                      ,"355"))
            array.add(PickerClass("Algeria"                                      ,"213"))
            array.add(PickerClass("American Samoa"                               ,"1684"))
            array.add(PickerClass("Andorra"                                      ,"376"))
            array.add(PickerClass("Angola"                                       ,"244"))
            array.add(PickerClass("Anguilla"                                     ,"1264"))
            array.add(PickerClass("Antigua and Barbuda"                          ,"1268"))
            array.add(PickerClass("Argentina"                                    ,"54"))
            array.add(PickerClass("Armenia"                                      ,"374"))
            array.add(PickerClass("Aruba"                                        ,"297"))
            array.add(PickerClass("Ascension"                                    ,"247"))
            array.add(PickerClass("Australia"                                    ,"61"))
            array.add(PickerClass("Australian External Territories"              ,"672"))
            array.add(PickerClass("Austria"                                      ,"43"))
            array.add(PickerClass("Azerbaijan"                                   ,"994"))
            array.add(PickerClass("Bahamas"                                      ,"1242"))
            array.add(PickerClass("Bahrain"                                      ,"973"))
            array.add(PickerClass("Bangladesh"                                   ,"880"))
            array.add(PickerClass("Barbados"                                     ,"1246"))
            array.add(PickerClass("Barbuda"                                      ,"1268"))
            array.add(PickerClass("Belarus"                                      ,"375"))
            array.add(PickerClass("Belgium"                                      ,"32"))
            array.add(PickerClass("Belize"                                       ,"501"))
            array.add(PickerClass("Benin"                                        ,"229"))
            array.add(PickerClass("Bermuda"                                      ,"1441"))
            array.add(PickerClass("Bhutan"                                       ,"975"))
            array.add(PickerClass("Bolivia"                                      ,"591"))
            array.add(PickerClass("Bosnia and Herzegovina"                       ,"387"))
            array.add(PickerClass("Botswana"                                     ,"267"))
            array.add(PickerClass("Brazil"                                       ,"55"))
            array.add(PickerClass("British Indian Ocean Territory"               ,"246"))
            array.add(PickerClass("British Virgin Islands"                       ,"1284"))
            array.add(PickerClass("Brunei"                                       ,"673"))
            array.add(PickerClass("Bulgaria"                                     ,"359"))
            array.add(PickerClass("Burkina Faso"                                 ,"226"))
            array.add(PickerClass("Burundi"                                      ,"257"))
            array.add(PickerClass("Cambodia"                                     ,"855"))
            array.add(PickerClass("Cameroon"                                     ,"237"))
            array.add(PickerClass("Canada"                                       ,"1"))
            array.add(PickerClass("Cape Verde"                                   ,"238"))
            array.add(PickerClass("Cayman Islands"                               ,"345"))
            array.add(PickerClass("Central African Republic"                     ,"236"))
            array.add(PickerClass("Chad"                                         ,"235"))
            array.add(PickerClass("Chile"                                        ,"56"))
            array.add(PickerClass("China"                                        ,"86"))
            array.add(PickerClass("Christmas Island"                             ,"61"))
            array.add(PickerClass("Cocos-Keeling Islands"                        ,"61"))
            array.add(PickerClass("Colombia"                                     ,"57"))
            array.add(PickerClass("Comoros"                                      ,"269"))
            array.add(PickerClass("Congo"                                        ,"242"))
            array.add(PickerClass("Congo, Dem. Rep. of (Zaire)"                  ,"243"))
            array.add(PickerClass("Cook Islands"                                 ,"682"))
            array.add(PickerClass("Costa Rica"                                   ,"506"))
            array.add(PickerClass("Croatia"                                      ,"385"))
            array.add(PickerClass("Cuba"                                         ,"53"))
            array.add(PickerClass("Curacao"                                      ,"599"))
            array.add(PickerClass("Cyprus"                                       ,"537"))
            array.add(PickerClass("Czech Republic"                               ,"420"))
            array.add(PickerClass("Denmark"                                      ,"45"))
            array.add(PickerClass("Diego Garcia"                                 ,"246"))
            array.add(PickerClass("Djibouti"                                     ,"253"))
            array.add(PickerClass("Dominica"                                     ,"1767"))
            array.add(PickerClass("Dominican Republic 1"                         ,"1809"))
            array.add(PickerClass("Dominican Republic 2"                         ,"1829"))
            array.add(PickerClass("Dominican Republic 3"                         ,"1849"))
            array.add(PickerClass("East Timor"                                   ,"670"))
            array.add(PickerClass("Easter Island"                                ,"56"))
            array.add(PickerClass("Ecuador"                                      ,"593"))
            array.add(PickerClass("Egypt"                                        ,"20"))
            array.add(PickerClass("El Salvador"                                  ,"503"))
            array.add(PickerClass("Equatorial Guinea"                            ,"240"))
            array.add(PickerClass("Eritrea"                                      ,"291"))
            array.add(PickerClass("Estonia"                                      ,"372"))
            array.add(PickerClass("Ethiopia"                                     ,"251"))
            array.add(PickerClass("Falkland Islands"                             ,"500"))
            array.add(PickerClass("Faroe Islands"                                ,"298"))
            array.add(PickerClass("Fiji"                                         ,"679"))
            array.add(PickerClass("Finland"                                      ,"358"))
            array.add(PickerClass("France"                                       ,"33"))
            array.add(PickerClass("French Antilles"                              ,"596"))
            array.add(PickerClass("French Guiana"                                ,"594"))
            array.add(PickerClass("French Polynesia"                             ,"689"))
            array.add(PickerClass("Gabon"                                        ,"241"))
            array.add(PickerClass("Gambia"                                       ,"220"))
            array.add(PickerClass("Georgia"                                      ,"995"))
            array.add(PickerClass("Germany"                                      ,"49"))
            array.add(PickerClass("Ghana"                                        ,"233"))
            array.add(PickerClass("Gibraltar"                                    ,"350"))
            array.add(PickerClass("Greece"                                       ,"30"))
            array.add(PickerClass("Greenland"                                    ,"299"))
            array.add(PickerClass("Grenada"                                      ,"1473"))
            array.add(PickerClass("Guadeloupe"                                   ,"590"))
            array.add(PickerClass("Guam"                                         ,"1671"))
            array.add(PickerClass("Guatemala"                                    ,"502"))
            array.add(PickerClass("Guinea"                                       ,"224"))
            array.add(PickerClass("Guinea-Bissau"                                ,"245"))
            array.add(PickerClass("Guyana"                                       ,"595"))
            array.add(PickerClass("Haiti"                                        ,"509"))
            array.add(PickerClass("Honduras"                                     ,"504"))
            array.add(PickerClass("Hong Kong SAR China"                          ,"852"))
            array.add(PickerClass("Hungary"                                      ,"36"))
            array.add(PickerClass("Iceland"                                      ,"354"))
            array.add(PickerClass("India"                                        ,"91"))
            array.add(PickerClass("Indonesia"                                    ,"62"))
            array.add(PickerClass("Iran"                                         ,"98"))
            array.add(PickerClass("Iraq"                                         ,"964"))
            array.add(PickerClass("Ireland"                                      ,"353"))
            array.add(PickerClass("Italy"                                        ,"39"))
            array.add(PickerClass("Ivory Coast"                                  ,"225"))
            array.add(PickerClass("Jamaica"                                      ,"1876"))
            array.add(PickerClass("Japan"                                        ,"81"))
            array.add(PickerClass("Jordan"                                       ,"962"))
            array.add(PickerClass("Kazakhstan"                                   ,"77"))
            array.add(PickerClass("Kenya"                                        ,"254"))
            array.add(PickerClass("Kiribati"                                     ,"686"))
            array.add(PickerClass("Kuwait"                                       ,"965"))
            array.add(PickerClass("Kyrgyzstan"                                   ,"996"))
            array.add(PickerClass("Laos"                                         ,"856"))
            array.add(PickerClass("Latvia"                                       ,"371"))
            array.add(PickerClass("Lebanon"                                      ,"961"))
            array.add(PickerClass("Lesotho"                                      ,"266"))
            array.add(PickerClass("Liberia"                                      ,"231"))
            array.add(PickerClass("Libya"                                        ,"218"))
            array.add(PickerClass("Liechtenstein"                                ,"423"))
            array.add(PickerClass("Lithuania"                                    ,"370"))
            array.add(PickerClass("Luxembourg"                                   ,"352"))
            array.add(PickerClass("Macau SAR China"                              ,"853"))
            array.add(PickerClass("Macedonia"                                    ,"389"))
            array.add(PickerClass("Madagascar"                                   ,"261"))
            array.add(PickerClass("Malawi"                                       ,"265"))
            array.add(PickerClass("Malaysia"                                     ,"60"))
            array.add(PickerClass("Maldives"                                     ,"960"))
            array.add(PickerClass("Mali"                                         ,"223"))
            array.add(PickerClass("Malta"                                        ,"356"))
            array.add(PickerClass("Marshall Islands"                             ,"692"))
            array.add(PickerClass("Martinique"                                   ,"596"))
            array.add(PickerClass("Mauritania"                                   ,"222"))
            array.add(PickerClass("Mauritius"                                    ,"230"))
            array.add(PickerClass("Mayotte"                                      ,"262"))
            array.add(PickerClass("Mexico"                                       ,"52"))
            array.add(PickerClass("Micronesia"                                   ,"691"))
            array.add(PickerClass("Midway Island"                                ,"1808"))
            array.add(PickerClass("Moldova"                                      ,"373"))
            array.add(PickerClass("Monaco"                                       ,"377"))
            array.add(PickerClass("Mongolia"                                     ,"976"))
            array.add(PickerClass("Montenegro"                                   ,"382"))
            array.add(PickerClass("Montserrat"                                   ,"1664"))
            array.add(PickerClass("Morocco"                                      ,"212"))
            array.add(PickerClass("Myanmar"                                      ,"95"))
            array.add(PickerClass("Namibia"                                      ,"264"))
            array.add(PickerClass("Nauru"                                        ,"674"))
            array.add(PickerClass("Nepal"                                        ,"977"))
            array.add(PickerClass("Netherlands"                                  ,"31"))
            array.add(PickerClass("Netherlands Antilles"                         ,"599"))
            array.add(PickerClass("Nevis"                                        ,"1869"))
            array.add(PickerClass("New Caledonia"                                ,"687"))
            array.add(PickerClass("New Zealand"                                  ,"64"))
            array.add(PickerClass("Nicaragua"                                    ,"505"))
            array.add(PickerClass("Niger"                                        ,"227"))
            array.add(PickerClass("Nigeria"                                      ,"234"))
            array.add(PickerClass("Niue"                                         ,"683"))
            array.add(PickerClass("Norfolk Island"                               ,"672"))
            array.add(PickerClass("North Korea"                                  ,"850"))
            array.add(PickerClass("Northern Mariana Islands"                     ,"1670"))
            array.add(PickerClass("Norway"                                       ,"47"))
            array.add(PickerClass("Oman"                                         ,"968"))
            array.add(PickerClass("Pakistan"                                     ,"92"))
            array.add(PickerClass("Palau"                                        ,"680"))
            array.add(PickerClass("Palestinian Territory"                        ,"970"))
            array.add(PickerClass("Panama"                                       ,"507"))
            array.add(PickerClass("Papua New Guinea"                             ,"675"))
            array.add(PickerClass("Paraguay"                                     ,"595"))
            array.add(PickerClass("Peru"                                         ,"51"))
            array.add(PickerClass("Philippines"                                  ,"63"))
            array.add(PickerClass("Poland"                                       ,"48"))
            array.add(PickerClass("Portugal"                                     ,"351"))
            array.add(PickerClass("Puerto Rico 1"                                ,"1787"))
            array.add(PickerClass("Puerto Rico 2"                                ,"1939"))
            array.add(PickerClass("Qatar"                                        ,"974"))
            array.add(PickerClass("Reunion"                                      ,"262"))
            array.add(PickerClass("Romania"                                      ,"40"))
            array.add(PickerClass("Russia"                                       ,"7"))
            array.add(PickerClass("Rwanda"                                       ,"250"))
            array.add(PickerClass("Samoa"                                        ,"685"))
            array.add(PickerClass("San Marino"                                   ,"378"))
            array.add(PickerClass("Saudi Arabia"                                 ,"966"))
            array.add(PickerClass("Senegal"                                      ,"221"))
            array.add(PickerClass("Serbia"                                       ,"381"))
            array.add(PickerClass("Seychelles"                                   ,"248"))
            array.add(PickerClass("Sierra Leone"                                 ,"232"))
            array.add(PickerClass("Singapore"                                    ,"65"))
            array.add(PickerClass("Slovakia"                                     ,"421"))
            array.add(PickerClass("Slovenia"                                     ,"386"))
            array.add(PickerClass("Solomon Islands"                              ,"677"))
            array.add(PickerClass("South Africa"                                 ,"27"))
            array.add(PickerClass("South Georgia and the South Sandwich Islands" ,"500"))
            array.add(PickerClass("South Korea"                                  ,"82"))
            array.add(PickerClass("Spain"                                        ,"34"))
            array.add(PickerClass("Sri Lanka"                                    ,"94"))
            array.add(PickerClass("Sudan"                                        ,"249"))
            array.add(PickerClass("Suriname"                                     ,"597"))
            array.add(PickerClass("Swaziland"                                    ,"268"))
            array.add(PickerClass("Sweden"                                       ,"46"))
            array.add(PickerClass("Switzerland"                                  ,"41"))
            array.add(PickerClass("Syria"                                        ,"963"))
            array.add(PickerClass("Taiwan"                                       ,"886"))
            array.add(PickerClass("Tajikistan"                                   ,"992"))
            array.add(PickerClass("Tanzania"                                     ,"255"))
            array.add(PickerClass("Thailand"                                     ,"66"))
            array.add(PickerClass("Timor Leste"                                  ,"670"))
            array.add(PickerClass("Togo"                                         ,"228"))
            array.add(PickerClass("Tokelau"                                      ,"690"))
            array.add(PickerClass("Tonga"                                        ,"676"))
            array.add(PickerClass("Trinidad and Tobago"                          ,"1868"))
            array.add(PickerClass("Tunisia"                                      ,"216"))
            array.add(PickerClass("Turkey"                                       ,"90"))
            array.add(PickerClass("Turkmenistan"                                 ,"993"))
            array.add(PickerClass("Turks and Caicos Islands"                     ,"1649"))
            array.add(PickerClass("Tuvalu"                                       ,"688"))
            array.add(PickerClass("Uganda"                                       ,"256"))
            array.add(PickerClass("Ukraine"                                      ,"380"))
            array.add(PickerClass("United Arab Emirates"                         ,"971"))
            array.add(PickerClass("United Kingdom"                               ,"44"))
            array.add(PickerClass("United States"                                ,"1"))
            array.add(PickerClass("Uruguay"                                      ,"598"))
            array.add(PickerClass("U.S. Virgin Islands"                          ,"1340"))
            array.add(PickerClass("Uzbekistan"                                   ,"998"))
            array.add(PickerClass("Vanuatu"                                      ,"678"))
            array.add(PickerClass("Venezuela"                                    ,"58"))
            array.add(PickerClass("Vietnam"                                      ,"84"))
            array.add(PickerClass("Wake Island"                                  ,"1808"))
            array.add(PickerClass("Wallis and Futuna"                            ,"681"))
            array.add(PickerClass("Yemen"                                        ,"967"))
            array.add(PickerClass("Zambia"                                       ,"260"))
            array.add(PickerClass("Zanzibar"                                     ,"255"))
            array.add(PickerClass("Zimbabwe"                                     ,"263"))
            return array
        }

        fun getFlags(): ArrayList<FlagsClass> {
            val array = ArrayList<FlagsClass>()
            array.add(FlagsClass("AD", "🇦🇩"))
            array.add(FlagsClass("AE", "🇦🇪"))
            array.add(FlagsClass("AF", "🇦🇫"))
            array.add(FlagsClass("AG", "🇦🇬"))
            array.add(FlagsClass("AI", "🇦🇮"))
            array.add(FlagsClass("AL", "🇦🇱"))
            array.add(FlagsClass("AM", "🇦🇲"))
            array.add(FlagsClass("AO", "🇦🇴"))
            array.add(FlagsClass("AQ", "🇦🇶"))
            array.add(FlagsClass("AR", "🇦🇷"))
            array.add(FlagsClass("AS", "🇦🇸"))
            array.add(FlagsClass("AT", "🇦🇹"))
            array.add(FlagsClass("AU", "🇦🇺"))
            array.add(FlagsClass("AW", "🇦🇼"))
            array.add(FlagsClass("AX", "🇦🇽"))
            array.add(FlagsClass("AZ", "🇦🇿"))
            array.add(FlagsClass("BA", "🇧🇦"))
            array.add(FlagsClass("BB", "🇧🇧"))
            array.add(FlagsClass("BD", "🇧🇩"))
            array.add(FlagsClass("BE", "🇧🇪"))
            array.add(FlagsClass("BF", "🇧🇫"))
            array.add(FlagsClass("BG", "🇧🇬"))
            array.add(FlagsClass("BH", "🇧🇭"))
            array.add(FlagsClass("BI", "🇧🇮"))
            array.add(FlagsClass("BJ", "🇧🇯"))
            array.add(FlagsClass("BL", "🇧🇱"))
            array.add(FlagsClass("BM", "🇧🇲"))
            array.add(FlagsClass("BN", "🇧🇳"))
            array.add(FlagsClass("BO", "🇧🇴"))
            array.add(FlagsClass("BQ", "🇧🇶"))
            array.add(FlagsClass("BR", "🇧🇷"))
            array.add(FlagsClass("BS", "🇧🇸"))
            array.add(FlagsClass("BT", "🇧🇹"))
            array.add(FlagsClass("BV", "🇧🇻"))
            array.add(FlagsClass("BW", "🇧🇼"))
            array.add(FlagsClass("BY", "🇧🇾"))
            array.add(FlagsClass("BZ", "🇧🇿"))
            array.add(FlagsClass("CA", "🇨🇦"))
            array.add(FlagsClass("CC", "🇨🇨"))
            array.add(FlagsClass("CD", "🇨🇩"))
            array.add(FlagsClass("CF", "🇨🇫"))
            array.add(FlagsClass("CG", "🇨🇬"))
            array.add(FlagsClass("CH", "🇨🇭"))
            array.add(FlagsClass("CI", "🇨🇮"))
            array.add(FlagsClass("CK", "🇨🇰"))
            array.add(FlagsClass("CL", "🇨🇱"))
            array.add(FlagsClass("CM", "🇨🇲"))
            array.add(FlagsClass("CN", "🇨🇳"))
            array.add(FlagsClass("CO", "🇨🇴"))
            array.add(FlagsClass("CR", "🇨🇷"))
            array.add(FlagsClass("CU", "🇨🇺"))
            array.add(FlagsClass("CV", "🇨🇻"))
            array.add(FlagsClass("CW", "🇨🇼"))
            array.add(FlagsClass("CX", "🇨🇽"))
            array.add(FlagsClass("CY", "🇨🇾"))
            array.add(FlagsClass("CZ", "🇨🇿"))
            array.add(FlagsClass("DE", "🇩🇪"))
            array.add(FlagsClass("DJ", "🇩🇯"))
            array.add(FlagsClass("DK", "🇩🇰"))
            array.add(FlagsClass("DM", "🇩🇲"))
            array.add(FlagsClass("DO", "🇩🇴"))
            array.add(FlagsClass("DZ", "🇩🇿"))
            array.add(FlagsClass("EC", "🇪🇨"))
            array.add(FlagsClass("EE", "🇪🇪"))
            array.add(FlagsClass("EG", "🇪🇬"))
            array.add(FlagsClass("EH", "🇪🇭"))
            array.add(FlagsClass("ER", "🇪🇷"))
            array.add(FlagsClass("ES", "🇪🇸"))
            array.add(FlagsClass("ET", "🇪🇹"))
            array.add(FlagsClass("FI", "🇫🇮"))
            array.add(FlagsClass("FJ", "🇫🇯"))
            array.add(FlagsClass("FK", "🇫🇰"))
            array.add(FlagsClass("FM", "🇫🇲"))
            array.add(FlagsClass("FO", "🇫🇴"))
            array.add(FlagsClass("FR", "🇫🇷"))
            array.add(FlagsClass("GA", "🇬🇦"))
            array.add(FlagsClass("GB", "🇬🇧"))
            array.add(FlagsClass("GD", "🇬🇩"))
            array.add(FlagsClass("GE", "🇬🇪"))
            array.add(FlagsClass("GF", "🇬🇫"))
            array.add(FlagsClass("GG", "🇬🇬"))
            array.add(FlagsClass("GH", "🇬🇭"))
            array.add(FlagsClass("GI", "🇬🇮"))
            array.add(FlagsClass("GL", "🇬🇱"))
            array.add(FlagsClass("GM", "🇬🇲"))
            array.add(FlagsClass("GN", "🇬🇳"))
            array.add(FlagsClass("GP", "🇬🇵"))
            array.add(FlagsClass("GQ", "🇬🇶"))
            array.add(FlagsClass("GR", "🇬🇷"))
            array.add(FlagsClass("GS", "🇬🇸"))
            array.add(FlagsClass("GT", "🇬🇹"))
            array.add(FlagsClass("GU", "🇬🇺"))
            array.add(FlagsClass("GW", "🇬🇼"))
            array.add(FlagsClass("GY", "🇬🇾"))
            array.add(FlagsClass("HK", "🇭🇰"))
            array.add(FlagsClass("HM", "🇭🇲"))
            array.add(FlagsClass("HN", "🇭🇳"))
            array.add(FlagsClass("HR", "🇭🇷"))
            array.add(FlagsClass("HT", "🇭🇹"))
            array.add(FlagsClass("HU", "🇭🇺"))
            array.add(FlagsClass("ID", "🇮🇩"))
            array.add(FlagsClass("IE", "🇮🇪"))
            array.add(FlagsClass("IM", "🇮🇲"))
            array.add(FlagsClass("IN", "🇮🇳"))
            array.add(FlagsClass("IO", "🇮🇴"))
            array.add(FlagsClass("IQ", "🇮🇶"))
            array.add(FlagsClass("IR", "🇮🇷"))
            array.add(FlagsClass("IS", "🇮🇸"))
            array.add(FlagsClass("IT", "🇮🇹"))
            array.add(FlagsClass("JE", "🇯🇪"))
            array.add(FlagsClass("JM", "🇯🇲"))
            array.add(FlagsClass("JO", "🇯🇴"))
            array.add(FlagsClass("JP", "🇯🇵"))
            array.add(FlagsClass("KE", "🇰🇪"))
            array.add(FlagsClass("KG", "🇰🇬"))
            array.add(FlagsClass("KH", "🇰🇭"))
            array.add(FlagsClass("KI", "🇰🇮"))
            array.add(FlagsClass("KM", "🇰🇲"))
            array.add(FlagsClass("KN", "🇰🇳"))
            array.add(FlagsClass("KP", "🇰🇵"))
            array.add(FlagsClass("KR", "🇰🇷"))
            array.add(FlagsClass("KW", "🇰🇼"))
            array.add(FlagsClass("KY", "🇰🇾"))
            array.add(FlagsClass("KZ", "🇰🇿"))
            array.add(FlagsClass("LA", "🇱🇦"))
            array.add(FlagsClass("LB", "🇱🇧"))
            array.add(FlagsClass("LC", "🇱🇨"))
            array.add(FlagsClass("LI", "🇱🇮"))
            array.add(FlagsClass("LK", "🇱🇰"))
            array.add(FlagsClass("LR", "🇱🇷"))
            array.add(FlagsClass("LS", "🇱🇸"))
            array.add(FlagsClass("LT", "🇱🇹"))
            array.add(FlagsClass("LU", "🇱🇺"))
            array.add(FlagsClass("LV", "🇱🇻"))
            array.add(FlagsClass("LY", "🇱🇾"))
            array.add(FlagsClass("MA", "🇲🇦"))
            array.add(FlagsClass("MC", "🇲🇨"))
            array.add(FlagsClass("MD", "🇲🇩"))
            array.add(FlagsClass("ME", "🇲🇪"))
            array.add(FlagsClass("MF", "🇲🇫"))
            array.add(FlagsClass("MG", "🇲🇬"))
            array.add(FlagsClass("MH", "🇲🇭"))
            array.add(FlagsClass("MK", "🇲🇰"))
            array.add(FlagsClass("ML", "🇲🇱"))
            array.add(FlagsClass("MM", "🇲🇲"))
            array.add(FlagsClass("MN", "🇲🇳"))
            array.add(FlagsClass("MO", "🇲🇴"))
            array.add(FlagsClass("MP", "🇲🇵"))
            array.add(FlagsClass("MQ", "🇲🇶"))
            array.add(FlagsClass("MR", "🇲🇷"))
            array.add(FlagsClass("MS", "🇲🇸"))
            array.add(FlagsClass("MT", "🇲🇹"))
            array.add(FlagsClass("MU", "🇲🇺"))
            array.add(FlagsClass("MV", "🇲🇻"))
            array.add(FlagsClass("MW", "🇲🇼"))
            array.add(FlagsClass("MX", "🇲🇽"))
            array.add(FlagsClass("MY", "🇲🇾"))
            array.add(FlagsClass("MZ", "🇲🇿"))
            array.add(FlagsClass("NA", "🇳🇦"))
            array.add(FlagsClass("NC", "🇳🇨"))
            array.add(FlagsClass("NE", "🇳🇪"))
            array.add(FlagsClass("NF", "🇳🇫"))
            array.add(FlagsClass("NG", "🇳🇬"))
            array.add(FlagsClass("NI", "🇳🇮"))
            array.add(FlagsClass("NL", "🇳🇱"))
            array.add(FlagsClass("NO", "🇳🇴"))
            array.add(FlagsClass("NP", "🇳🇵"))
            array.add(FlagsClass("NR", "🇳🇷"))
            array.add(FlagsClass("NU", "🇳🇺"))
            array.add(FlagsClass("NZ", "🇳🇿"))
            array.add(FlagsClass("OM", "🇴🇲"))
            array.add(FlagsClass("PA", "🇵🇦"))
            array.add(FlagsClass("PE", "🇵🇪"))
            array.add(FlagsClass("PF", "🇵🇫"))
            array.add(FlagsClass("PG", "🇵🇬"))
            array.add(FlagsClass("PH", "🇵🇭"))
            array.add(FlagsClass("PK", "🇵🇰"))
            array.add(FlagsClass("PL", "🇵🇱"))
            array.add(FlagsClass("PM", "🇵🇲"))
            array.add(FlagsClass("PN", "🇵🇳"))
            array.add(FlagsClass("PR", "🇵🇷"))
            array.add(FlagsClass("PS", "🇵🇸"))
            array.add(FlagsClass("PT", "🇵🇹"))
            array.add(FlagsClass("PW", "🇵🇼"))
            array.add(FlagsClass("PY", "🇵🇾"))
            array.add(FlagsClass("QA", "🇶🇦"))
            array.add(FlagsClass("RE", "🇷🇪"))
            array.add(FlagsClass("RO", "🇷🇴"))
            array.add(FlagsClass("RS", "🇷🇸"))
            array.add(FlagsClass("RU", "🇷🇺"))
            array.add(FlagsClass("RW", "🇷🇼"))
            array.add(FlagsClass("SA", "🇸🇦"))
            array.add(FlagsClass("SB", "🇸🇧"))
            array.add(FlagsClass("SC", "🇸🇨"))
            array.add(FlagsClass("SD", "🇸🇩"))
            array.add(FlagsClass("SE", "🇸🇪"))
            array.add(FlagsClass("SG", "🇸🇬"))
            array.add(FlagsClass("SH", "🇸🇭"))
            array.add(FlagsClass("SI", "🇸🇮"))
            array.add(FlagsClass("SJ", "🇸🇯"))
            array.add(FlagsClass("SK", "🇸🇰"))
            array.add(FlagsClass("SL", "🇸🇱"))
            array.add(FlagsClass("SM", "🇸🇲"))
            array.add(FlagsClass("SN", "🇸🇳"))
            array.add(FlagsClass("SO", "🇸🇴"))
            array.add(FlagsClass("SR", "🇸🇷"))
            array.add(FlagsClass("SS", "🇸🇸"))
            array.add(FlagsClass("ST", "🇸🇹"))
            array.add(FlagsClass("SV", "🇸🇻"))
            array.add(FlagsClass("SX", "🇸🇽"))
            array.add(FlagsClass("SY", "🇸🇾"))
            array.add(FlagsClass("SZ", "🇸🇿"))
            array.add(FlagsClass("TC", "🇹🇨"))
            array.add(FlagsClass("TD", "🇹🇩"))
            array.add(FlagsClass("TF", "🇹🇫"))
            array.add(FlagsClass("TG", "🇹🇬"))
            array.add(FlagsClass("TH", "🇹🇭"))
            array.add(FlagsClass("TJ", "🇹🇯"))
            array.add(FlagsClass("TK", "🇹🇰"))
            array.add(FlagsClass("TL", "🇹🇱"))
            array.add(FlagsClass("TM", "🇹🇲"))
            array.add(FlagsClass("TN", "🇹🇳"))
            array.add(FlagsClass("TO", "🇹🇴"))
            array.add(FlagsClass("TR", "🇹🇷"))
            array.add(FlagsClass("TT", "🇹🇹"))
            array.add(FlagsClass("TV", "🇹🇻"))
            array.add(FlagsClass("TW", "🇹🇼"))
            array.add(FlagsClass("TZ", "🇹🇿"))
            array.add(FlagsClass("UA", "🇺🇦"))
            array.add(FlagsClass("UG", "🇺🇬"))
            array.add(FlagsClass("UM", "🇺🇲"))
            array.add(FlagsClass("US", "🇺🇸"))
            array.add(FlagsClass("UY", "🇺🇾"))
            array.add(FlagsClass("UZ", "🇺🇿"))
            array.add(FlagsClass("VA", "🇻🇦"))
            array.add(FlagsClass("VC", "🇻🇨"))
            array.add(FlagsClass("VE", "🇻🇪"))
            array.add(FlagsClass("VG", "🇻🇬"))
            array.add(FlagsClass("VI", "🇻🇮"))
            array.add(FlagsClass("VN", "🇻🇳"))
            array.add(FlagsClass("VU", "🇻🇺"))
            array.add(FlagsClass("WF", "🇼🇫"))
            array.add(FlagsClass("WS", "🇼🇸"))
            array.add(FlagsClass("YE", "🇾🇪"))
            array.add(FlagsClass("YT", "🇾🇹"))
            array.add(FlagsClass("ZA", "🇿🇦"))
            array.add(FlagsClass("ZM", "🇿🇲"))
            array.add(FlagsClass("ZW", "🇿🇼"))
            return array
        }

        fun getDate(context: Context, date: String, from: String, to: String): String {
            try {
                val locale = Locale(context.getString(R.string.language))
                val dateParser = SimpleDateFormat(from, Locale.ENGLISH)
                val dateFormatter = SimpleDateFormat(to, locale)
                val date = dateParser.parse(date)!!
                val dateString = dateFormatter.format(date)
                return dateString
            } catch (_: Exception) {

            }
            return date
        }

        fun getPhone(editText: EditText): String {
            val phone = editText.text.toString().replace(" ", "")
                .replace("-", "")
                .replace("(", "")
                .replace(")", "")

            return phone
        }
    }
}
